### ISSUE TITLE
Reshade.json is broken

### ISSUE THREAD

**Issue by pakdev** [lptstr/lptstr-scoop#10]
[Looks](https://github.com/lptstr/open-scoop/blob/master/bucket/reshade.json) like a bad/incomplete merge. Causes `scoop search` to fail:

![image](https://user-images.githubusercontent.com/1248927/53032891-6857b400-3435-11e9-8e45-d99198eb4c2a.png)

**Comment by kiedtl** [comment]
oops.

**Comment by kiedtl** [comment]
Fixed in commit c020e4c6600597d71fbaba649d2bdfb0ea5b1473
